---
baseURL: https://www.danbaghilovici.xyz
languageCode: en-us
theme: hugo-devblog-premium-theme
title: AAAAAAAAA
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/en
    languageName: English
    languageCode: en-US
    languageFlagImgPath: ''
    weight: 0
    menu:
      main:
        - url: "/"
          name: siteNavAboutText
          weight: 1
          pre: fa-user
        - url: "/blog"
          name: siteNavBlogText
          weight: 2
          pre: fa-blog
#        - url: "/portfolio"
#          name: siteNavPortfolioText
#          weight: 3
#          pre: fa-laptop
  ro:
    contentDir: content/ro
    languageName: Română
    languageCode: ro-RO
    languageFlagImgPath: ''
    weight: 1
    menu:
      main:
        - url: "/"
          name: siteNavAboutText
          weight: 1
          pre: fa-user
        - url: "/blog"
          name: siteNavBlogText
          weight: 2
          pre: fa-blog
#        - url: "/portofoliu"
#          name: siteNavPortfolioText
#          weight: 3
#          pre: fa-laptop
  es:
    contentDir: content/es
    languageName: Español
    languageCode: es-ES
    languageFlagImgPath: ''
    weight: 2
    menu:
      main:
        - url: "/"
          name: siteNavAboutText
          weight: 1
          pre: fa-user
        - url: "/blog"
          name: siteNavBlogText
          weight: 2
          pre: fa-blog
#        - url: "/portofolio"
#          name: siteNavPortfolioText
#          weight: 3
#          pre: fa-laptop
sitemap:
  changefreq: weekly
  priority: 0.5
canonifyURLs: true
params:
  monthNames:
    1: "janvier"
    2: "février"
    3: "mars"
    4: "avril"
    5: "mai"
    6: "juin"
    7: "juillet"
    8: "août"
    9: "septembre"
    10: "octobre"
    11: "novembre"
    12: "décembre"
  useDarkMode: true
  siteNavIconsClassesInOrder:
    - fa-user
    - fa-blog
    - fa-laptop
  ownerFirstName: Dan
  ownerLastName: Baghilovici
  ownerEmail:
    - contact@danbaghilovici.xyz
    - dan.baghilovici@gmail.com
  ownerPhone:
    - "+40 770 662 188"
  ownerLocation: Romania
  ownerWebsite: www.danbaghilovici.xyz
  ownerSocialLinks:
    - class: fa-twitter
      tooltip: ''
      link: https://twitter.com/dntzbgh
    - class: fa-linkedin-in
      tooltip: ''
      link: https://www.linkedin.com/in/dan-baghilovici-a137251b8
    - class: fa-github-alt
      tooltip: ''
      link: https://github.com/dntzbgh
  ownerSkillsSet:
    - title: Javascript
      description: ownerSkillsJavascript
      iconClass: fa-js-square
      libs:
        - title: Angular
          description: ownerSkillsAngular
          iconClass: fa-angular
        - title: Node.js
          description: ownerSkillNode
          iconClass: fa-node-js
    - title: Python
      description: ownerSkillsPython
      iconClass: fa-python
      libs:
        - title: Django
          description: ownerSkillsDjango
          iconClass: fa-python
  ownerWorkExperience:
    - jobTitle: resumeJobTitleVlinde
      company:
        name: Vlinde Transylvania
        website: www.vlinde.de
        icon: ''
      period:
        from: '2019'
        to: jobPeriodPresent
      description: resumeJobDescriptionVlinde
      list:
        - resumeJobBulletVlinde1
        - resumeJobBulletVlinde2
  ownerProjects:
    - name: Project name
      motto: resumeProjectMotto0
      description: resumeProjectDescription0
      link: ''
      open: true
  ownerEducation:
    - period: a
